### PR TITLE
initial upgrade to grails-3.3.1

### LINKED ISSUE #27: Upgrade to grails 3.3.1
badge

Please upgrade application.properties to grails version 3.3.1, see also https://grails.org/download.html

### PR DESCRIPTION
**Pull request by kstuart**
Upgrading to grails 3.3.1 from the current codebase is not a trivial task as the architecture of grails has changed significantly from the version currently used in this app. This PR covers the primary effort needed to get openthesaurus up and running on grails 3.3.1 and opens the door for further refactoring/compatibility with grails 3.3 onward.

To the best of my knowledge it is mostly working as expected but given the big leap I expect there will be more minor updates/tweaking needed. Ideally this PR would be merged into a grails-3.3 branch, others can then easily contribute such smaller updates where they can, and tickets can be raised against the branch to better track issues specific to grails 3.3.

Resolves #27

---
You can see see an example of how to setup mail SMTP account in the `grails.mail` section of `application.yml`.

*Versions used:*

```
grails-3.3.1
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (Zulu 8.31.0.1-linux64) (build 1.8.0_181-b02)
OpenJDK 64-Bit Server VM (Zulu 8.31.0.1-linux64) (build 25.181-b02, mixed mode)
```

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks, I could make it work locally and mostly it looks good. I will try to run a load test later with more traffic. Some small issues:

- recent design fixes are still missing, do you think you can merge them with git despite the many changes?
- Some strings are English only (`No exact matches for '...'`, `Successfully logged in as admin`)

**Comment by kstuart** [comment]
Locales should be working now.

I'll take a look at merging with your master branch, please hold off adding anything new for now :)

**Comment by kstuart** [comment]
Should now be up to date, the file `views/synset/_ad.gsp` is missing which causes failures. can you publish that file?

it is used here: https://github.com/danielnaber/openthesaurus/blob/db31e9b4da62ffcf827fe407a93b97e0b957d3c8/grails-app/views/synset/search.gsp#L81

**Comment by danielnaber** [comment]
I have added that file as an empty file (plus two small changes that I forgot to push).

**Comment by kstuart** [comment]
updates made.

investigating an authentication issue.

**Comment by kstuart** [comment]
Ah, an oversight on my part, when refactoring authentication I forgot to check if any of the methods were being used outside of authentication, works in latest commit.

**Comment by danielnaber** [comment]
Thanks, that's working now. `messages_de.properties` is in Dutch so when I set `thesaurus.serverId=de` I get a Dutch website. I guess that's not on purpose?

**Comment by kstuart** [comment]
hehe, sorry not familiar with the languages, so in master branch `messages.properties` is german, I'm not on the system so can't fix that right now, but if you do the following so you can continue testing I'll echo the changes in the next commit sometime this evening or tomorrow morning.

in folder `grails-app/i18n` copy `messages_de.properties` to `messages_nl.properties`, and `messages.properties` to `messages_de.properties`

That should work.

**Comment by kstuart** [comment]
It depends a little on what you're trying to achieve, if you simply want to serve some static files I suggest putting them in `src/main/resources/public` (you'll need to create that folder), or a subfolder thereof, prefix the URI with `static`.

so if you create the file 'license.txt' in `src/main/resources/public`, you can then fetch the file with `http://<server>/static/license.txt`.

You can also use the folder `src/main/webapp` if you prefer. If you really want to serve them from root URI you can configure that by setting `grails.resources.pattern` to '/**', but to avoid any issues I suggest you stick with the *static* prefix.

**Comment by danielnaber** [comment]
Thanks, most things seem to work. Could you check why `/synonyme/search?q=Hand&format=application/json&substring=true` produces an error? (`no such property: substringtermsList for class: groovy.json.StreamingJsonBuilder$StreamingJsonDelegate.`)

**Comment by kstuart** [comment]
> Thanks, most things seem to work. Could you check why `/synonyme/search?q=Hand&format=application/json&substring=true` produces an error?

I'm not seeing that error, please provide a minimal dataset that reproduces the issue:

screenshot from 2018-11-08 13-02-54

**Comment by kstuart** [comment]
> Another small issue: `jquery-ui.css` isn't found on pages like /synonyme/edit/12833

It appears to be there for me? Though the page isn't using any of it's rules.

screenshot from 2018-11-08 13-26-48

**Comment by danielnaber** [comment]
> I'm not seeing that error, please provide a minimal dataset/instructions to reproduce the issue:

It's Just a upper/lowercase typo, line 525 needs to be `substringTermsList`, not `substringtermsList`

**Comment by kstuart** [comment]
Ok, thanks, I'll make that change. I've resolve the jquery-ui issue but will need to do some further asset resource cleanup, hopefully will commit the changes a little later today, it maybe this evening before I have the time available though.

**Comment by kstuart** [comment]
Actually it doesn't look like I need to do as much refactoring as initially thought.

Give it a go, limited testing but it appears all page resources are now being loaded.

**Comment by danielnaber** [comment]
Okay, so this may be the last small issue: there's a cookie banner script which requires a hard-coded path to what is until now `https://www.openthesaurus.de/static/css/dark-bottom.css`. Can this be excluded from the process that seems to auto-generate names? (like `icon-mail-2afcd7b9accdd40774dfda0d22a76458.png`)

**Comment by kstuart** [comment]
the files digest is added to the filename to invalidate caches when the content changes, however using the original filename should also work.

That said I've removed the reliance on a hard-coded path so it should now work the same as other assets.

**Comment by danielnaber** [comment]
Thanks, the new code is low live on https://www.openthesaurus.de, if it works fine for 2-3 days, we can merge it into the official repo.

**Comment by danielnaber** [comment]
Sorry I'm coming up with more stuff, but this is probably easy to solve for you (while I would need to research quite a bit): there are still links to urls like https://www.openthesaurus.de/synset/edit/41933, these should redirect to https://www.openthesaurus.de/synonyme/edit/41933

**Comment by kstuart** [comment]
I'm not sure what you mean, if I visit https://www.openthesaurus.de/synset/edit/41933 it does redirect to https://www.openthesaurus.de/synonyme/edit/41933 ?

**Comment by danielnaber** [comment]
When on the edit page and trying to create an association, I get:

```
2018-11-14 22:35:58 ERROR [nio-8080-exec-6] ilsExceptionResolver : HibernateException occurred when processing request: [GET] /static/synset/ajaxSearch - parameters:
q: haus
linkTypeName: Assoziation
No Session found for current thread. Stacktrace follows:

org.hibernate.HibernateException: No Session found for current thread
        at org.grails.orm.hibernate.GrailsSessionContext.currentSession(GrailsSessionContext.java:117)
        at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:688)
        at org.grails.orm.hibernate.HibernateSession.createQuery(HibernateSession.java:177)
        at org.grails.orm.hibernate.HibernateSession.createQuery(HibernateSession.java:170)
        at org.grails.datastore.gorm.finders.AbstractFindByFinder.buildQuery(AbstractFindByFinder.java:44)
        at org.grails.datastore.gorm.finders.AbstractFindByFinder$1.doInSession(AbstractFindByFinder.java:29)
        at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
        at org.grails.datastore.gorm.finders.AbstractFinder.execute(AbstractFinder.java:42)
        at org.grails.datastore.gorm.finders.AbstractFindByFinder.doInvokeInternal(AbstractFindByFinder.java:27)
        at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:254)
        at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:392)
        at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:181)
        at openthesaurus.SSOForForumInterceptor.getDurationSession(SSOForForumInterceptor.groovy:43)
        at openthesaurus.SSOForForumInterceptor.before(SSOForForumInterceptor.groovy:18)
        at org.grails.plugins.web.interceptors.GrailsInterceptorHandlerInterceptorAdapter.preHandle(GrailsInterceptorHandlerInterceptorAdapter.groovy:77)
        at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:133)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:962)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
ot-create-association

**Comment by danielnaber** [comment]
Yes, it's fixed now, thanks.

**Comment by danielnaber** [comment]
> I'm not sure what you mean, if I visit https://www.openthesaurus.de/synset/edit/41933 it does redirect to https://www.openthesaurus.de/synonyme/edit/41933 ?

This was somehow related to my session it, logging out and logging in again seems to have fixed it.

**Comment by danielnaber** [comment]
I think it's working now - do you want to update the pull request so it can be merged? (Currently github says "This branch has conflicts that must be resolved")

**Comment by kstuart** [comment]
Awesome, should now be mergeable :)

**Comment by danielnaber** [comment]
I have found a regression, could you have a look at https://github.com/danielnaber/openthesaurus/issues/57 maybe?

**Comment by kstuart** [comment]
np, done.

Please close #27 now the code has been merged, so the stakeholders know they can update and I can claim the bounty.

Just message any further regressions in this ticket so I get notified.

**Comment by kstuart** [comment]
Did you setup smtp server?
See first PR comment

Sent from my iPhone

On 17 Nov 2018, at 12:24, Daniel Naber <notifications@github.com<mailto:notifications@github.com>> wrote:


I've opened an issue about sending mails at #60<https://github.com/danielnaber/openthesaurus/issues/60>

**Comment by danielnaber** [comment]
> Did you setup smtp server? See first PR comment

Sorry, I missed that, it's working now. See https://github.com/danielnaber/openthesaurus/issues/61 for another minor issue.

**Pull request merged**
